# Generated by Django 3.1.1 on 2020-09-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Mike', max_length=255),
            preserve_default=False,
        ),
    ]
